### ISSUE TITLE
Movie reordering causes movies to jump

### ISSUE THREAD

**Issue by charwking** [charwking/movie-club#115]
The arrows on the my-movies page should allow the users to reorder their movies in any way they want. There appears to be some wonkiness where the movies are jumping over each other instead of just moving one space:

![badarrows](https://cloud.githubusercontent.com/assets/5176154/8559254/9e442292-24d0-11e5-9134-8167900d2c48.gif)

This is the behavior on both Chrome and Safari.

**Comment by charwking** [comment]
This appears to be a problem with the `order` attribute of movie objects getting set to non-unique values. I believe this was the problem with @AsmodeusXI not being able to reorder his movies. I manually updated this for affected users, but there's no guarantee it doesn't occur again.

The root cause still needs to be determined.

**Comment by squarejaw** [comment]
I think this might be caused by the movie `order` not being reset when one is removed from the top of a list.
https://github.com/charwking/movie-club/blob/master/src/hostMeeting/hostMeeting.controller.js#L64

This ends up causing new movies to be added with a duplicated `order`.
https://github.com/charwking/movie-club/blob/master/src/myMovies/myMovies.controller.js#L18

**Comment by charwking** [comment]
Brilliant @squarejaw! Nice find. I (or some other enterprising individual) will get that fixed.

**Comment by charwking** [comment]
Fixed by @squarejaw in #125
