### ISSUE TITLE
Weight movie selection

### ISSUE THREAD

**Issue by charwking** [charwking/movie-club#91]
When selecting a movie, don't just randomly select from the present participants. Instead, weight the participants by number of attendances since the last time one of their movies was selected.

Note that this will prevent anyone from having their movie selected twice.

**Comment by BrandonCKrueger** [comment]
`Moving comments from Ross's word document to issue topic:`

**Increases Chances of Being Picked**
* Attending Meetup
* Watching Movie
* Guesses Who Submitted Movies? -cool, pushes more interactions  / community
* Most interesting lunch items 
* Dressing up or otherwise decorating themselves in accordance with the theme of the movie
* Using the github issue that exists for this topic already to discuss ideas. :)


**Decreases Chance of Being Picked**
* Not Attending Meetup
* Higher Count of Your Movies Being Picked in the Past
* Mismatched socks
* Wearing manager hat ←-- LOL
* Incorrectly guessing who submitted the movie
* Picking a movie that EVERYONE (people in the meeting other than you) considered to be a bad movie

**Comment by BrandonCKrueger** [comment]
I was thinking this over today... in order to get things off and rolling I think keeping it simple would be our best bet.  Something real simple like:

* Members gain five (5) raffle ticket when they attend a meeting
* Raffle tickets only decrease when a user's movie is selected (in which case it resets to 0)
* Tickets would be added when the meeting host clicks the `Select Movie` button that way new members stand a chance as having their movie selected.


In the future we could add addition ways to earn raffle tickets like guessing movies and what not.

**Comment by charwking** [comment]
Thanks for moving these notes here @BrandonCKrueger! I think you're on to something, although I'm curious why we would hand out 5 "tickets" for attendance, instead of 1.

**Comment by ttonyan10** [comment]
LOL ---> "Picking a movie that EVERYONE considers to be a bad movie" YES!!!

**Comment by BrandonCKrueger** [comment]
@charwking Only to give us additional wiggle room to add *bonus* tickets like +1 ticket for guessing who put in the movie or rating the movie.  Enough that there's incentive, but not enough to completely skew the probabilities.

Obviously we'd need to tweak the numbers based off input (I'm not sure what the Movie Club bylaws say about number of member approval required to pass such an amendment :stuck_out_tongue:).  We could start with one, but I figured since we'd most likely include 'silly' prize tickets we just user a higher base off the bat.

**Comment by charwking** [comment]
I see your point @BrandonCKrueger. Ideally I'd like to see a history of attendances and movie selections kept, and then attendances since last movie selection would be a couple queries on this. In lieu of building all that out, I'd prefer to see a count of attendances since last movie selection.

When determine how much "weight" each person has, that can use some coefficients to balance things out. e.g. userMovieWeight = (attendanceWeight * numAttendancesSinceSelection) + (watchWeight * numMoviesWatchedSinceSelection)

I like this approach because it keeps things independent -- a bucket full of indistinguishable "tickets" is hard to dissect and reuse for other purposes.

As for the bylaws -- I have a strong preference to keep things as objective as possible. It will take some convincing to get me to go along with weighting factors that involve subjective things like individual preference (e.g. "good" movies, popular lunch items, etc.)

I'm willing to bend to the majority opinion though -- as long as it's a majority of active club participants -- not active Github participants. :)
